#!/usr/bin/env python3
"""Generate project-local Codex skills from harness rp skill docs."""

from __future__ import annotations

import argparse
import os
import json
import shutil
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "docs" / "skills"
DEST_DIR = ROOT / ".codex" / "skills"
USER_SKILLS_DIR = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "skills"


def split_frontmatter(path: Path) -> tuple[dict[str, str], str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError(f"{path} missing YAML frontmatter")

    end = text.find("\n---\n", 4)
    if end == -1:
        raise ValueError(f"{path} missing closing YAML frontmatter")

    raw_meta = text[4:end].splitlines()
    body = text[end + len("\n---\n") :]
    meta: dict[str, str] = {}

    for line in raw_meta:
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        value = value.strip()
        if (value.startswith("'") and value.endswith("'")) or (
            value.startswith('"') and value.endswith('"')
        ):
            value = value[1:-1]
        meta[key.strip()] = value

    return meta, body


def codex_description(name: str, original: str) -> str:
    suffix = (
        f" Use when Codex should run or follow the harness {name} stage, "
        f"or when the user invokes /{name}, ${name}, or asks for this workflow step."
    )
    return f"{original.rstrip('.')}.{suffix}"


def adapt_body_for_codex(body: str) -> str:
    replacements = {
        "Agent 툴의 서브에이전트": "`spawn_agent` 서브에이전트",
        "Agent 툴 오류": "spawn_agent 오류",
        "Doc Agent가 PRD 본문 갱신": "문서 작성자가 PRD 본문 갱신",
        "Doc Agent 재투입": "문서 작성자 재투입",
        "Doc Agent 재작성": "문서 작성자 재작성",
        "Doc Agent": "문서 작성자",
        "Dev Agent 재투입": "개발자 재투입",
        "Dev Agent": "개발자",
    }

    adapted = body
    for before, after in replacements.items():
        adapted = adapted.replace(before, after)

    return adapted


def render_skill(source: Path) -> str:
    name = source.stem
    meta, body = split_frontmatter(source)
    original_description = meta.get("description")
    if not original_description:
        raise ValueError(f"{source} missing description")

    description = codex_description(name, original_description)
    rel_source = source.relative_to(ROOT)

    adapted_body = adapt_body_for_codex(body)

    return (
        "---\n"
        f"name: {name}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n"
        "---\n\n"
        f"> Generated from `{rel_source}`. Do not edit this file directly; run "
        "`python3 scripts/sync-codex-skills.py` after changing the Claude skill source.\n\n"
        "## Codex Adapter Notes\n\n"
        "- Treat this as the Codex project-local equivalent of the matching Claude `/rp-*` skill.\n"
        "- Resolve copied relative links against the source file under `docs/skills/` when needed.\n"
        "- Do not record Claude-only `.claude` hooks or slash commands as executed unless they actually ran.\n"
        "- Use Codex `spawn_agent` for independent review when a review step requires role separation.\n"
        "- Runtime is the reviewer: never call Claude for an extra cross-runtime review.\n"
        "- Reflect Codex-Lead review findings into the PRD body itself; do not write `review-codex-*.md` or `review-claude-*.md` evidence files.\n\n"
        + adapted_body
    )


def build_tree(target: Path) -> list[str]:
    target.mkdir(parents=True, exist_ok=True)
    names: list[str] = []

    for source in sorted(SOURCE_DIR.glob("rp-*.md")):
        name = source.stem
        names.append(name)
        skill_dir = target / name
        skill_dir.mkdir(parents=True, exist_ok=True)
        (skill_dir / "SKILL.md").write_text(render_skill(source), encoding="utf-8")

    return names


def sync() -> None:
    if DEST_DIR.exists():
        for child in DEST_DIR.iterdir():
            if child.is_dir() and child.name.startswith("rp-"):
                shutil.rmtree(child)
    build_tree(DEST_DIR)


def install_user() -> None:
    USER_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    names = [source.stem for source in sorted(SOURCE_DIR.glob("rp-*.md"))]

    for name in names:
        target = DEST_DIR / name
        link = USER_SKILLS_DIR / name
        if link.is_symlink() or not link.exists():
            if link.exists() or link.is_symlink():
                link.unlink()
            link.symlink_to(target, target_is_directory=True)
            continue
        print(f"skip existing non-symlink: {link}", file=sys.stderr)


def check() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dest = Path(tmp) / "skills"
        names = build_tree(tmp_dest)

        missing: list[str] = []
        changed: list[str] = []

        for name in names:
            expected = tmp_dest / name / "SKILL.md"
            actual = DEST_DIR / name / "SKILL.md"
            if not actual.exists():
                missing.append(name)
                continue
            if actual.read_text(encoding="utf-8") != expected.read_text(encoding="utf-8"):
                changed.append(name)

        extra = sorted(
            child.name
            for child in DEST_DIR.glob("rp-*")
            if child.is_dir() and child.name not in names
        )

    if missing or changed or extra:
        if missing:
            print("missing:", ", ".join(missing), file=sys.stderr)
        if changed:
            print("out-of-date:", ", ".join(changed), file=sys.stderr)
        if extra:
            print("extra:", ", ".join(extra), file=sys.stderr)
        return 1

    print(f"Codex skills in sync: {len(names)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify generated skills are current")
    parser.add_argument(
        "--install-user",
        action="store_true",
        help="symlink generated rp-* skills into $CODEX_HOME/skills for Codex discovery",
    )
    args = parser.parse_args()

    if args.check:
        return check()

    sync()
    if args.install_user:
        install_user()
    print(f"Generated Codex skills in {DEST_DIR.relative_to(ROOT)}")
    if args.install_user:
        print(f"Installed user skill links in {USER_SKILLS_DIR}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
